# Generated by Django 5.0.3 on 2024-04-05 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0008_alter_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('QB', 'Quarterback'), ('RB', 'Running Back'), ('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('LT', 'Left Tackle'), ('LG', 'Left Guard'), ('C', 'Center'), ('RG', 'Right Guard'), ('RT', 'Right Tackle'), ('DT', 'Defensive Tackle'), ('EDGE', 'Edge'), ('LB', 'Line Backer'), ('CB', 'Corner Back'), ('S', 'Safety'), ('KR', 'Kick Returner'), ('PR', 'Punt Returner'), ('K', 'Kicker'), ('P', 'Punter'), ('BENCH', 'Bench')], max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosters.position')),
            ],
        ),
        migrations.CreateModel(
            name='RosterSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Bench', 'Bench')], max_length=50)),
                ('player', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_spot', to='rosters.player')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosters.position')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_spots', to='leagues.team')),
            ],
            options={
                'unique_together': {('team', 'position', 'player')},
            },
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosters.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.team')),
            ],
            options={
                'unique_together': {('team', 'player')},
            },
        ),
    ]
