# Generated by Django 5.0.3 on 2024-04-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0002_player_college_player_experience_player_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='jersey_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
