# Generated by Django 5.0.3 on 2024-04-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0003_player_jersey_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='jersey_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
