# Generated by Django 5.0.3 on 2024-04-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0005_alter_position_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='is_kick_returner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='position',
            name='is_punt_returner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='position',
            name='is_skill_position',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(choices=[('QB', 'Quarterback'), ('RB', 'Running Back'), ('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('T', 'Tackle'), ('G', 'Guard'), ('C', 'Center'), ('DT', 'Defensive Tackle'), ('EDGE', 'Edge'), ('LB', 'Linebacker'), ('CB', 'Cornerback'), ('S', 'Safety'), ('KR', 'Kick Returner'), ('PR', 'Punt Returner'), ('K', 'Kicker'), ('P', 'Punter')], max_length=5, unique=True),
        ),
    ]
