# Generated by Django 5.0.3 on 2024-04-06 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0006_position_is_kick_returner_position_is_punt_returner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosterspot',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rosters.position'),
        ),
    ]
