# Generated by Django 5.0.3 on 2024-04-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0008_alter_position_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='is_kick_returner',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='is_punt_returner',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='is_skill_position',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
