# Generated by Django 5.0.3 on 2024-04-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0010_alter_position_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='defensive',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='offensive',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='special_teams',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
