# Generated by Django 5.0.3 on 2024-04-11 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_alter_team_name'),
        ('rosters', '0011_position_defensive_position_offensive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosterspot',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roster_spots', to='leagues.league'),
        ),
    ]
