# Generated by Django 5.0.3 on 2024-04-13 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_alter_team_name'),
        ('rosters', '0012_rosterspot_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rosterspot',
            name='league',
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters_teams', to='leagues.league')),
            ],
        ),
        migrations.AlterField(
            model_name='rosterspot',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_spots', to='rosters.team'),
        ),
    ]
