# Generated by Django 5.0.3 on 2024-04-13 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_alter_team_name'),
        ('rosters', '0013_remove_rosterspot_league_team_alter_rosterspot_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosterspot',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_spots', to='leagues.team'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
