# Generated by Django 5.0.3 on 2024-04-13 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_alter_team_name'),
        ('rosters', '0017_delete_teamplayer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rosterspot',
            unique_together={('team', 'position')},
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(choices=[('QB', 'Quarterback'), ('RB', 'Running Back'), ('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('T', 'Tackle'), ('G', 'Guard'), ('C', 'Center'), ('DT', 'Defensive Tackle'), ('DE', 'Defensive End'), ('LB', 'Linebacker'), ('CB', 'Cornerback'), ('S', 'Safety'), ('K', 'Kicker'), ('P', 'Punter')], max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='rosterspot',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_spots', to='rosters.player'),
        ),
        migrations.AlterField(
            model_name='rosterspot',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Bench', 'Bench'), ('Injured', 'Injured')], max_length=50),
        ),
    ]
