# Generated by Django 5.0.3 on 2024-04-13 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_alter_team_name'),
        ('rosters', '0019_alter_rosterspot_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosterspot',
            name='player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_spot', to='rosters.player'),
        ),
        migrations.AlterField(
            model_name='rosterspot',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Bench', 'Bench')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='rosterspot',
            unique_together={('team', 'position')},
        ),
    ]
