# Generated by Django 5.0.3 on 2024-04-13 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0020_alter_rosterspot_player_alter_rosterspot_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rosterspot',
            unique_together=set(),
        ),
    ]
