# Generated by Django 5.0.4 on 2024-04-14 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0014_alter_nflgame_game_date_alter_nflgame_game_time'),
        ('rosters', '0024_alter_rosterspot_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Bench', 'Bench')], max_length=50)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosters.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='leagues.team')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.week')),
            ],
        ),
    ]
