# Generated by Django 5.0.4 on 2024-04-15 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0014_alter_nflgame_game_date_alter_nflgame_game_time'),
        ('rosters', '0025_rosterentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosterspot',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.week'),
        ),
        migrations.DeleteModel(
            name='RosterEntry',
        ),
    ]
