# Generated by Django 5.0.4 on 2024-04-15 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0015_alter_matchup_week'),
        ('rosters', '0026_rosterspot_week_delete_rosterentry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rosterspot',
            unique_together={('team', 'player', 'week')},
        ),
    ]
