# Generated by Django 5.0.4 on 2024-04-18 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0015_alter_matchup_week'),
        ('rosters', '0028_rosterspot_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nfl_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='leagues.nflteam'),
        ),
    ]
