# Generated by Django 5.0.3 on 2024-03-31 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_remove_league_password_alter_league_commissioner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='league',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='league_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='JoinRequest',
        ),
    ]
