# Generated by Django 5.0.3 on 2024-03-31 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_league_is_public_league_password_alter_league_member_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='password',
            new_name='league_password',
        ),
    ]
