# Generated by Django 5.0.3 on 2024-04-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_alter_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(help_text='Week number in the season')),
                ('start_date', models.DateField(help_text='Start date of the fantasy week')),
                ('end_date', models.DateField(help_text='End date of the fantasy week')),
                ('lock_time', models.DateTimeField(help_text='Deadline after which no roster changes can be made')),
                ('is_active', models.BooleanField(default=False, help_text='Whether this week is currently active')),
            ],
            options={
                'verbose_name_plural': 'Weeks',
                'ordering': ['week_number'],
            },
        ),
    ]
