# Generated by Django 5.0.4 on 2024-04-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0009_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFLTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(max_length=3, unique=True)),
            ],
        ),
    ]
