# Generated by Django 5.0.4 on 2024-04-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0011_nflgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflgame',
            name='game_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflgame',
            name='game_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
