# Generated by Django 5.0.4 on 2024-04-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0012_nflgame_game_date_alter_nflgame_game_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date of the fantasy week', null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='lock_time',
            field=models.DateTimeField(blank=True, help_text='Deadline after which no roster changes can be made', null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date of the fantasy week', null=True),
        ),
    ]
