# Generated by Django 5.0.4 on 2024-04-15 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0014_alter_nflgame_game_date_alter_nflgame_game_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='leagues.week'),
        ),
    ]
