export {default as Home} from './Home'
export {default as Login} from './Login'
export {default as Profile} from './Profile'
export {default as Signup} from './Signup'
export {default as About} from './About'
export {default as CreateLeagues} from './CreateLeagues' 
export {default as JoinLeagues} from './JoinLeagues'
export {default as MyLeagues} from './MyLeagues'
export {default as LeagueHomePage} from './LeagueHome'

