# Generated by Django 5.0.3 on 2024-04-11 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0008_alter_team_name'),
        ('rosters', '0011_position_defensive_position_offensive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPerformanceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('touchdowns', models.IntegerField(default=0)),
                ('fumble_lost', models.IntegerField(default=0)),
                ('penalty', models.IntegerField(default=0)),
                ('pass_yards', models.IntegerField(default=0)),
                ('interceptions', models.IntegerField(default=0)),
                ('yards', models.IntegerField(default=0)),
                ('receptions', models.IntegerField(default=0)),
                ('drop', models.IntegerField(default=0)),
                ('sack_given', models.IntegerField(default=0)),
                ('qb_hit', models.IntegerField(default=0)),
                ('qb_hurry', models.IntegerField(default=0)),
                ('tackle', models.IntegerField(default=0)),
                ('tackle_assist', models.IntegerField(default=0)),
                ('sack', models.IntegerField(default=0)),
                ('batted_pass', models.IntegerField(default=0)),
                ('forced_fumble', models.IntegerField(default=0)),
                ('pass_breakup', models.IntegerField(default=0)),
                ('missed_tackle', models.IntegerField(default=0)),
                ('XP', models.IntegerField(default=0)),
                ('XP_missed', models.IntegerField(default=0)),
                ('FG', models.IntegerField(default=0)),
                ('FG_missed', models.IntegerField(default=0)),
                ('FG_40_49', models.IntegerField(default=0)),
                ('FG_50_59', models.IntegerField(default=0)),
                ('FG_60_plus', models.IntegerField(default=0)),
                ('punt_inside20', models.IntegerField(default=0)),
                ('punt_ypa', models.IntegerField(default=0)),
                ('punt_ypr', models.IntegerField(default=0)),
                ('kick_return_yards', models.IntegerField(default=0)),
                ('punt_return_yards', models.IntegerField(default=0)),
                ('muffed', models.IntegerField(default=0)),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.matchup')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosters.player')),
            ],
        ),
    ]
