# Generated by Django 5.0.4 on 2024-04-15 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0015_alter_matchup_week'),
        ('rosters', '0027_alter_rosterspot_unique_together'),
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerPerformanceStats',
            new_name='PlayerPerformance',
        ),
    ]
