# Generated by Django 5.0.4 on 2024-04-17 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_rename_playerperformancestats_playerperformance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerperformance',
            old_name='matchup',
            new_name='week',
        ),
    ]
